apiVersion: apps/v1
kind: Deployment
metadata:
  name: outlay-notbroken-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: outlay-notbroken-pod
  template:
    metadata:
      labels:
        app: outlay-notbroken-pod
    spec:
      containers:
      - name: outlay-notbroken-container
        image: serhii11yanchuk/outlay-notbroken:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
