apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  selector:
    matchLabels:
      app: producer-pod
  template:
    metadata:
      labels:
        app: producer-pod
    spec:
      containers:
      - name: producer-container
        image: producermicroserv
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
